### ISSUE TITLE
слово "Dashboard"

### ISSUE THREAD

**Issue by blozixdextr** [ifrond/adtw#14]
необходимо сделать слово "Dashboard" не ссылкой, а просто текстом, мы пытались найти в исходном коде этот момент, но не получилось 
![image](https://cloud.githubusercontent.com/assets/2786905/10245425/a98deb4e-6907-11e5-866f-a126ed153fc5.png)

**Comment by blozixdextr** [comment]
И сам баланс также должен быть простым текстом, без ссылки

**Comment by ifrond** [comment]
done
