### ISSUE TITLE
Ввод промокода для стримера

### ISSUE THREAD

**Issue by blozixdextr** [ifrond/adtw#17]
1) необходимо добавить возможность редактировать е-мейл через админку , чтоб можно было "удалить" пользователя

2) пришел непонятный емейл, что заказчик отменил заказ у самого себя. Хотя заказчик отменял заказ у одного из стримеров.
![image](https://cloud.githubusercontent.com/assets/2786905/10264776/d4f94bf6-6a16-11e5-9d91-9d9fb3972f8b.png)

3) После регистрации стримера необходимо включить все галочки размеров баннеров. Чтоб по умолчанию все 3 размера баннеров были включены. А стример уже решал, выключить или нет эти галочки. Также нужно определить язык браузера пользователя и , если он английский , то выставить галочку английского языка по-умолчанию (это сразу после регистрации стримера)

4) Ввод промокода для стримера:  план таков -
 - мы сообщаем стримерам промокод, например "ADD25USD" и они его вводят на странице сразу после регистрации (страница где они задают язык стрима и прочее)
 - стримеру ложиться на баланс 25 долл , но он их может снять тогда, когда у него будет общий заработок 100 долл 
- необходимо в самом балансе четко обозначить, что 25 долл заблокированы, до момента , когда стример накопит 100 долл всего , тогда он сможет обналичивать 25 долл

**Comment by ifrond** [comment]
subs 2 and 3 are done

**Comment by ifrond** [comment]
sub 1 is done
Для того, чтобы отвязать клиента достаточно изменить email, чтобы отвязать стримера нужно поменять еще и oauth_id на что-нибудь не цифровое, например, '-' или 'none'

**Comment by ifrond** [comment]
sub 4 done
