### ISSUE TITLE
Немного переделать систему отображения баннеров

### ISSUE THREAD

**Issue by blozixdextr** [ifrond/adtw#19]
Столкнулся с тем, что стримеры не знают как вырезать зелёный цвет .
Можно сделать для каждого баннера строго определенный размер откываемого окна:

Например , для баннера  300х250 необходимо открыть окно строго размерами 300х250 , а стример захватит его и будет стримить.

Достаточно только 3 стандартных размера, которые у нас уже есть.

**Comment by ifrond** [comment]
done
